#!/usr/bin/env bash

## wlogout actions

# Ask for confirmation
cdialog () {
	yad --title='Confirmar?' --borders=4 --center --fixed --undecorated --button=Si:0 --button=No:1 --text="Estás Seguro?" --text-align=center
}

if [[ "$1" == '--shutdown' ]]; then
	cdialog
	if [[ "$?" == 0 ]]; then
		systemctl poweroff
    else
		exit
    fi
elif [[ "$1" == '--reboot' ]]; then
	cdialog
	if [[ "$?" == 0 ]]; then
		systemctl reboot
    else
		exit
    fi
elif [[ "$1" == '--hibernate' ]]; then
	cdialog
	if [[ "$?" == 0 ]]; then
		# hypridle's before_sleep_cmd will handle locking
		systemctl hibernate
    else
		exit
    fi
elif [[ "$1" == '--lock' ]]; then
	# This is for manual locking, separate from hypridle's idle lock
	~/.local/bin/scripts/lockscreen
elif [[ "$1" == '--suspend' ]]; then
	if [[ "$?" == 0 ]]; then
		# hypridle's before_sleep_cmd will handle locking
		systemctl suspend
    else
		exit
    fi
elif [[ "$1" == '--logout' ]]; then
	cdialog
	if [[ "$?" == 0 ]]; then
		kill -9 -1
    else
		exit
    fi
fi
